{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry-api.secretName" . }}
  labels:
    {{- include "telemetry-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.connectionString | quote }}
{{- end }}
