{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cqrs-client.secretName" . }}
  labels:
    {{- include "cqrs-client.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecretKey }}: {{ .Values.api.key | quote }}
{{- end }}
