apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-client.fullname" . }}
  labels:
    {{- include "customer-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "customer-client.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
